repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        exclude: ^docs/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        exclude: ^docs/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        exclude: ^docs/
        additional_dependencies:
          - types-python-jose
          - pydantic>=2.0
          - types-redis
          - fastapi>=0.109.0
        args: ["app", "tests"]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest --ignore=docs --ignore=tests/test_integration
        pass_filenames: false
        language: system
        types: [python]
        stages: [pre-commit]
        always_run: true
