# Docker-based pre-commit configuration
# All hooks run inside Docker containers - no local dependencies required except Docker

repos:
  # Basic file checks still run via pre-commit for speed, but could be dockerized too
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: trailing-whitespace

  # All Python tools run via bouy test command
  - repo: local
    hooks:
      - id: black-docker
        name: black (docker)
        entry: bash -c './bouy --programmatic --quiet test --black'
        pass_filenames: false
        language: system
        types: [python]
        exclude: ^docs/

      - id: ruff-docker
        name: ruff (docker)
        entry: bash -c './bouy --programmatic --quiet test --ruff'
        pass_filenames: false
        language: system
        types: [python]
        exclude: ^docs/

      - id: mypy-docker
        name: mypy (docker)
        entry: bash -c './bouy --programmatic --quiet test --mypy'
        pass_filenames: false
        language: system
        types: [python]
        exclude: ^docs/

      - id: pytest-docker
        name: pytest (docker)
        entry: bash -c './bouy --programmatic --quiet test --pytest'
        pass_filenames: false
        language: system
        types: [python]
        always_run: true
