#!/bin/bash
# Run all 87 new scrapers via AWS Step Functions
./bouy scraper --aws --prod \
  forgotten_harvest_mi \
  second_harvest_nw_nc \
  inter_faith_food_shuttle_nc \
  food_bank_of_iowa_ia \
  food_bank_of_the_rio_grande_valley_tx \
  fulfill_nj \
  food_bank_of_eastern_michigan_mi \
  food_bank_of_north_alabama_al \
  access_food_share_or \
  armstrong_county_community_action_pa \
  atcaa_ca \
  brazos_valley_food_bank_tx \
  capeco_food_share_or \
  cca_regional_food_bank_or \
  ceo_weinberg_northeast_regional_foodbank_pa \
  channel_one_regional_food_bank_mn \
  coastal_bend_food_bank_tx \
  columbia_pacific_food_bank_or \
  community_connection_ne_oregon_or \
  community_food_bank_of_san_benito_county_ca \
  community_harvest_food_bank_in \
  fayette_county_community_action_pa \
  feeding_the_foothills_ca \
  feeding_the_valley_food_bank_ga \
  food_bank_of_east_alabama_al \
  food_bank_of_north_central_arkansas_ar \
  food_bank_of_northern_indiana_in \
  food_bank_of_northwest_indiana_in \
  food_bank_of_siouxland_ia \
  food_bank_of_south_jersey_nj \
  food_bank_of_the_albemarle_nc \
  food_bank_of_the_golden_crescent_tx \
  food_bank_of_west_central_texas_tx \
  food_for_families_pa \
  food_for_lane_county_or \
  food_for_people_ca \
  food_pantry_network_licking_county_oh \
  food_share_lincoln_county_or \
  galveston_county_food_bank_tx \
  georgia_mountain_food_bank_ga \
  golden_harvest_food_bank_ga \
  greater_lansing_food_bank_mi \
  hacap_food_reservoir_ia \
  harvest_regional_food_bank_ar \
  hoosier_hills_food_bank_in \
  imperial_valley_food_bank_ca \
  indiana_county_community_action_pa \
  interfaith_food_bank_amador_ca \
  josephine_county_food_bank_or \
  klamath_lake_food_bank_or \
  linn_benton_food_share_or \
  marion_polk_food_share_or \
  mendocino_food_nutrition_ca \
  merced_county_food_bank_ca \
  mercer_street_friends_nj \
  middle_georgia_community_food_bank_ga \
  montgomery_county_food_bank_tx \
  neighborimpact_or \
  northeast_iowa_food_bank_ia \
  norwescap_food_bank_nj \
  resource_connection_food_bank_ca \
  river_valley_regional_food_bank_ar \
  se_ohio_foodbank_oh \
  second_harvest_clark_champaign_logan_oh \
  second_harvest_food_bank_of_nw_pennsylvania_pa \
  second_harvest_mahoning_valley_oh \
  second_harvest_north_central_oh \
  second_harvest_nw_nc \
  second_harvest_of_coastal_georgia_ga \
  second_harvest_of_south_georgia_ga \
  second_harvest_se_nc \
  selma_area_food_bank_al \
  shared_harvest_foodbank_oh \
  slo_food_bank_ca \
  south_coast_food_share_or \
  south_michigan_food_bank_mi \
  south_plains_food_bank_tx \
  south_texas_food_bank_tx \
  southeast_texas_food_bank_tx \
  terre_haute_catholic_charities_in \
  the_foodbank_inc_oh \
  ucan_food_bank_or \
  west_alabama_food_bank_al \
  west_ohio_food_bank_oh \
  wiregrass_area_food_bank_al \
  yamhill_cap_or \
  yolo_food_bank_ca \
  yuba_sutter_food_bank_ca
