# Codespaces-specific overrides for PostgreSQL compatibility
services:
  db:
    environment:
      # PostgreSQL environment variables for Codespaces
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devcontainer
      - POSTGRES_DB=pantry_pirate_radio
      # Use md5 authentication instead of trust for better security
      # The password is already set to 'devcontainer' which is acceptable for dev environments
      - POSTGRES_INITDB_ARGS=--auth-host=md5
      - POSTGRES_HOST_AUTH_METHOD=md5
    # Healthcheck with proper authentication
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=devcontainer pg_isready -U postgres -d pantry_pirate_radio"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    # Increase shared memory for PostgreSQL in Codespaces
    shm_size: 128mb
    
  # Reduce resource requirements for Codespaces
  app:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
          
  worker:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M