# Docker Compose override file for running with database initialization
# This runs the replay utility to populate the database from HAARRRvest data
#
# Usage:
#   docker-compose --profile with-init up -d
#   OR
#   docker-compose -f docker-compose.yml -f docker-compose.with-init.yml up -d
#
# Startup sequence:
#   1. db (PostgreSQL) starts
#   2. haarrrvest-publisher starts and clones HAARRRvest repository
#   3. db-init runs replay to populate database from HAARRRvest data
#   4. All other services start once db-init is healthy

services:
  # Override db-init to remove the profile restriction when this overlay is used
  db-init:
    profiles: []  # Remove profile restriction to always include this service
  # Update service dependencies to wait for db-init instead of just db
  app:
    depends_on:
      db-init:
        condition: service_healthy
      cache:
        condition: service_started

  worker:
    depends_on:
      db-init:
        condition: service_healthy
      cache:
        condition: service_started

  recorder:
    depends_on:
      db-init:
        condition: service_healthy
      cache:
        condition: service_started
      haarrrvest-publisher:
        condition: service_healthy

  scraper:
    depends_on:
      db-init:
        condition: service_healthy
      cache:
        condition: service_started

  reconciler:
    depends_on:
      db-init:
        condition: service_healthy
      cache:
        condition: service_started

  haarrrvest-publisher:
    depends_on:
      db-init:
        condition: service_healthy
      db:
        condition: service_healthy
      cache:
        condition: service_started