name: Bouy Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'bouy'
      - 'bouy-functions.sh'
      - 'tests/test_bouy*.py'
      - '.github/workflows/bouy-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'bouy'
      - 'bouy-functions.sh'
      - 'tests/test_bouy*.py'
      - '.github/workflows/bouy-tests.yml'

jobs:
  bouy-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Install Docker Compose
        run: |
          # Install Docker Compose v2
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version

      - name: Run bouy unit tests
        run: |
          # Make bouy executable
          chmod +x ./bouy
          chmod +x ./bouy-functions.sh

          # Run the bouy unit tests directly (not in Docker)
          poetry run pytest tests/test_bouy_unit.py tests/test_bouy_simplified.py -v

  bouy-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Install Docker Compose
        run: |
          # Install Docker Compose v2
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version

      - name: Run bouy integration tests with mocking
        run: |
          # Make scripts executable
          chmod +x ./bouy
          chmod +x ./bouy-functions.sh
          chmod +x tests/shell/fixtures/mock_compose.sh

          # Run the bouy integration tests with mocked docker compose
          poetry run pytest tests/test_bouy_integration.py tests/test_bouy_docker.py -v

  bouy-shell-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run bouy shell tests
        run: |
          # Make scripts executable
          chmod +x ./bouy
          chmod +x ./bouy-functions.sh
          chmod +x tests/test_bouy.sh
          chmod +x tests/shell/fixtures/mock_compose.sh

          # Run the shell test suite
          ./tests/test_bouy.sh

  bouy-help-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test bouy help and version
        run: |
          chmod +x ./bouy

          # Test help command
          ./bouy --help

          # Test version command
          ./bouy --version

          # Test programmatic mode
          ./bouy --programmatic --help

          # Test JSON mode
          ./bouy --json --help || true  # May fail if no services running