name: CD - Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags for unified image
        id: tags
        run: |
          set -euo pipefail  # Exit on error, undefined variables, pipe failures
          
          TAGS=""
          DATE=$(date +%Y%m%d)
          SHA="${{ github.sha }}"
          
          # Convert image name to lowercase (Docker requirement)
          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          
          # Add tags based on branch/event type
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:latest"
            TAGS="${TAGS},${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:main"
          fi
          
          # Always add SHA tag for traceability
          TAGS="${TAGS},${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:${SHA:0:7}"
          TAGS="${TAGS},${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:${DATE}"
          
          # Version tags for releases and tags
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            TAGS="${TAGS},${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:${VERSION}"
            TAGS="${TAGS},${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:stable"
          fi
          
          # Remove leading comma if present and validate result
          TAGS="${TAGS#,}"
          if [[ -z "$TAGS" ]]; then
            echo "Error: No tags were generated"
            exit 1
          fi
          
          # Output results
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "Generated tags: ${TAGS}"

      - name: Build and push unified Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/images/app/Dockerfile
          target: unified
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'release' }}
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.ref_name }}
          # Ensure no secrets are passed as build args

  build-datasette:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=datasette-
            type=raw,value=datasette-latest,enable={{is_default_branch}}
            type=raw,value=datasette-{{sha}},enable=true
            type=raw,value=datasette-{{date 'YYYYMMDD'}},enable={{is_default_branch}}

      - name: Build and push Datasette Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/images/datasette/Dockerfile
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    needs: [build-and-push, build-datasette]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true