name: CD - Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target: [app, worker, recorder, scraper, test, datasette-exporter]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ matrix.target }}-latest,enable={{is_default_branch}}
            type=raw,value=${{ matrix.target }}-{{sha}},enable=true
            type=raw,value=${{ matrix.target }}-{{branch}},enable=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.ref_name }}

  build-datasette:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=datasette-{{branch}}-
            type=raw,value=datasette-latest,enable={{is_default_branch}}
            type=raw,value=datasette-{{sha}},enable=true

      - name: Build and push Datasette Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.datasette
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    needs: [build-and-push, build-datasette]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: |
            ## Docker Images

            This release includes the following Docker images:
            
            ### Application Services
            - `ghcr.io/${{ github.repository }}:app-${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository }}:worker-${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository }}:recorder-${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository }}:scraper-${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository }}:datasette-exporter-${{ github.ref_name }}`
            - `ghcr.io/${{ github.repository }}:datasette-${{ github.ref_name }}`
            
            ### Testing
            - `ghcr.io/${{ github.repository }}:test-${{ github.ref_name }}`

            ### Pull Images
            ```bash
            docker pull ghcr.io/${{ github.repository }}:app-${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository }}:worker-${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository }}:recorder-${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository }}:scraper-${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository }}:datasette-exporter-${{ github.ref_name }}
            docker pull ghcr.io/${{ github.repository }}:datasette-${{ github.ref_name }}
            ```

            ### Docker Compose Usage
            Update your `.env` file:
            ```env
            DOCKER_REGISTRY=ghcr.io/${{ github.repository }}
            DOCKER_TAG=${{ github.ref_name }}
            ```