name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  checks: write

env:
  PYTHONPATH: ${{ github.workspace }}
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pirate
  POSTGRES_DB: pantry_pirate_radio
  DATABASE_URL: postgresql://postgres:pirate@db:5432/pantry_pirate_radio
  REDIS_URL: redis://cache:6379/0
  LLM_PROVIDER: openai
  LLM_MODEL_NAME: google/gemini-2.0-flash-001
  LLM_TEMPERATURE: 0.7
  LLM_MAX_TOKENS: 64768
  LLM_RESPONSE_FORMAT: json_object
  LLM_TIMEOUT: 30
  CI: true  # Skip heavy database initialization

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate cache key
        id: cache-key
        run: echo "key=${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}" >> $GITHUB_OUTPUT

  formatting-and-linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run file checks
        run: |
          # Check YAML files
          find . -name "*.yaml" -o -name "*.yml" | xargs -I {} python -c "import yaml; yaml.safe_load(open('{}'))"
          # Check TOML files
          find . -name "*.toml" | xargs -I {} python -c "import tomllib; tomllib.load(open('{}', 'rb'))"
          # Check for large files (>500KB)
          find . -type f -size +500k -not -path "./.git/*" -not -path "./.*" | head -10
          # Check for trailing whitespace
          find . -name "*.py" -exec grep -l '[[:space:]]$' {} \; | head -10
      - name: Run Black formatter check
        run: poetry run black --check app tests

      - name: Run Ruff linter
        run: poetry run ruff check app tests


  mypy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run MyPy type checker
        run: poetry run mypy app tests

  pytest:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create test environment file
        run: |
          # Create .env.test file
          cp .env.example .env.test
          # Update database password for CI
          sed -i 's/POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=pirate/' .env.test
          # Update database URLs for CI test environment
          sed -i 's|postgresql+psycopg2://postgres:your_secure_password@db:5432/pantry_pirate_radio|postgresql+psycopg2://postgres:pirate@db:5432/test_pantry_pirate_radio|' .env.test
          sed -i 's|redis://cache:6379/0|redis://cache:6379/1|' .env.test
          # Set API key from GitHub secret if available
          if [ -n "${{ secrets.OPENROUTER_API_KEY }}" ]; then
            sed -i 's/your_api_key_here/${{ secrets.OPENROUTER_API_KEY }}/' .env.test
          fi
          # Disable HAARRRvest push for tests
          sed -i 's/PUBLISHER_PUSH_ENABLED=.*/PUBLISHER_PUSH_ENABLED=false/' .env.test
          # Also create .env for services
          cp .env.test .env
          # Export POSTGRES_PASSWORD for bouy to use
          echo "POSTGRES_PASSWORD=pirate" >> $GITHUB_ENV

      - name: Run tests
        run: |
          chmod +x ./bouy
          # Run with --programmatic for better CI output
          ./bouy --programmatic test --pytest

      - name: Extract coverage data
        run: |
          # Coverage reports are already in the local directory from bouy test
          echo "Coverage reports available:"
          ls -la coverage.* || echo "No coverage files found"

      - name: Display coverage summary
        run: |
          echo "Coverage report generated:"
          if [ -f coverage.xml ]; then
            echo "✅ XML coverage report: coverage.xml"
          fi
          if [ -f coverage.json ]; then
            echo "✅ JSON coverage report: coverage.json"
          fi

      - name: Restore coverage baseline from cache
        uses: actions/cache/restore@v4
        with:
          path: .coverage-baseline
          key: coverage-baseline-${{ github.ref_name }}
          restore-keys: |
            coverage-baseline-main
            coverage-baseline-

      - name: Check coverage ratcheting
        run: |
          # Run coverage check with ratcheting using bouy
          ./bouy test --coverage

      - name: Save coverage baseline to cache
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/cache/save@v4
        with:
          path: .coverage-baseline
          key: coverage-baseline-main-${{ github.run_number }}

      - name: Stop services
        if: always()
        run: ./bouy down

  vulture:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run Vulture dead code check
        run: poetry run vulture app tests .vulture_whitelist --min-confidence 80

  bandit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run Bandit security check
        run: poetry run bandit -r app

  safety:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run Safety security check
        run: poetry run safety check

  pip-audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run pip-audit security check
        run: poetry run pip-audit

  xenon:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry config virtualenvs.create false
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run Xenon complexity check
        run: poetry run xenon --max-absolute F --max-modules F --max-average E app